# -*- coding: utf-8 -*-
"""Codsoft task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12DhVNBQkdCwt8bb6tEcBb_Q8Es19ynkq
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/car_purchasing.csv', encoding='latin1')

data = data.drop(['customer name', 'customer e-mail', 'country'], axis=1)

X = data.drop(['car purchase amount'], axis=1)
y = data['car purchase amount']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)

new_customer_data = pd.DataFrame({
    'gender': [0],
    'age': [46.58474463],
    'annual Salary': [58139.2591],
    'credit card debt': [3440.823799],
    'net worth': [630059.0274]
})

predicted_purchase_amount = model.predict(new_customer_data)
print("Predicted Car Purchase Amount:", predicted_purchase_amount[0])

